### ISSUE TITLE
API Broken?

### ISSUE THREAD

**Issue by kimtakala** [treyg/very-bad-media#1]
The website seems to have stopped updating all together after 27.2. Easy fix?

**Comment by treyg** [comment]
Interesting. I'll look into it when I get a minute. It should be an easy fix though. Thanks for bringing it up!

**Comment by treyg** [comment]
@kimtakala Just got this fixed. Should be good to go. Thanks for bringing it up!

**Comment by kimtakala** [comment]
No worries. Tysm for doing this for free for the community <3Ytv. Kim TakalaOn 21 Jun 2024 2.14, Trey Gordon ***@***.***> wrote:
@kimtakala Just got this fixed. Should be good to go. Thanks for bringing it up!
